"""Credits: a node advertises every feed and every UI output it uses.

Brief reference: section 7 (integrations). KNP-0 I2 (provenance is never dropped).

A node that serves someone else's data says so, in a form the someone else can check. From
what a node holds - observations, Trooth scorecards, Modafied attestations - this module
writes one page: the feeds with their licence and the attribution text their catalog entry
asks for, links to the Trooth scorecard pages the node's cards came from, and the Modafied
emblems embedded exactly the way Modafied's emblems page prescribes (the full emblem, linked
to its scorecard page) with Modafied's notice under them. Nothing on the page is hand-written:
`kourob publish --credits` regenerates it from the store.
"""

from __future__ import annotations

import json
from collections.abc import Iterable
from typing import Any

from kourob.node import Node

__milestone__ = "M3"

TROOTH_SITE = "https://alexchouck-hash.github.io/trooth-site"
MODAFIED_SITE = "https://modafied.org"


def held(node: Node) -> dict[str, Any]:
    """The newest observation, scorecard and emblem per source this node holds."""
    store = node.store
    out: dict[str, Any] = {
        "node": node.manifest.identity.name,
        "sources": [],
        "scorecards": [],
        "emblems": [],
    }
    if store.stats("silver")["rows"] == 0:
        return out
    rows = store.query(
        "SELECT schema_ref, payload FROM silver WHERE schema_ref IN "
        "('observation.v1', 'scorecard.v1', 'emblem.v1') ORDER BY ts"
    ).to_pylist()
    newest: dict[tuple[str, str], dict[str, Any]] = {}
    for row in rows:
        payload = row["payload"]
        payload = json.loads(payload) if isinstance(payload, str) else payload
        newest[(row["schema_ref"], str(payload.get("source_id", "")))] = payload
    for (schema, source_id), p in sorted(newest.items()):
        if schema == "observation.v1":
            out["sources"].append(
                {
                    "source_id": source_id,
                    "url": p.get("source_url", ""),
                    "license": p.get("license", ""),
                    "source_timestamp": p.get("source_timestamp", ""),
                    "content_hash": p.get("content_hash", ""),
                }
            )
        elif schema == "scorecard.v1":
            out["scorecards"].append(
                {
                    "source_id": source_id,
                    "source_name": p.get("source_name", source_id),
                    "generated_at": p.get("generated_at", ""),
                    "freshness_p95_s": p.get("freshness_p95_s"),
                    "completeness_pct": p.get("completeness_pct"),
                    "page_url": f"{TROOTH_SITE}/scorecards/{source_id}",
                }
            )
        elif schema == "emblem.v1":
            out["emblems"].append(
                {
                    "source_id": source_id,
                    "source_name": p.get("source_name", source_id),
                    "grade": p.get("grade", ""),
                    "alt": p.get("emblem_alt", ""),
                    "full": p.get("emblem_full", ""),
                    "compact": p.get("emblem_compact", ""),
                    "page_url": p.get("scorecard_page_url", ""),
                    "trace_id": p.get("trace_id", ""),
                    "notice": p.get("notice", ""),
                }
            )
    return out


def markdown_emblem(emblem: dict[str, Any]) -> str:
    """The embed Modafied prescribes: the full emblem, linked to the scorecard page."""
    return f"[![{emblem['alt']}]({emblem['full']})]({emblem['page_url']})"


def credits_markdown(
    nodes: Iterable[Node], *, attribution: dict[str, str] | None = None, title: str = "Credits"
) -> str:
    """One page for a node or a whole set: the feeds, the Trooth cards, the Modafied emblems."""
    attribution = attribution or {}
    sources: dict[str, dict[str, Any]] = {}
    cards: dict[str, dict[str, Any]] = {}
    emblems: dict[str, dict[str, Any]] = {}
    held_by: dict[str, set[str]] = {}
    for node in nodes:
        c = held(node)
        for s in c["sources"]:
            sources.setdefault(s["source_id"], s)
            held_by.setdefault(s["source_id"], set()).add(c["node"])
        for s in c["scorecards"]:
            cards.setdefault(s["source_id"], s)
        for e in c["emblems"]:
            emblems.setdefault(e["source_id"], e)

    lines = [
        f"# {title}",
        "",
        "Generated by `kourob publish --credits` from what the nodes hold. Nothing here is "
        "hand-written; rebuild it and it says what is true then.",
        "",
    ]
    if sources:
        lines += [
            "## Data feeds, via Trooth",
            "",
            f"Delivered as signed provenance envelopes by [Trooth]({TROOTH_SITE}/), the single "
            "data connector and provenance pipe. Each feed's licence and attribution are its own.",
            "",
        ]
        for sid, s in sorted(sources.items()):
            card = cards.get(sid)
            page = f" · [Trooth scorecard]({card['page_url']})" if card else ""
            holders = ", ".join(sorted(held_by.get(sid, set())))
            lines.append(
                f"- **{sid}** — {attribution.get(sid) or sid} "
                f"({s['license'] or 'licence unstated'}). [source]({s['url']}){page}. "
                f"Held by {holders}."
            )
        lines.append("")
    if cards:
        lines += [
            "## UI outputs used: Trooth scorecards",
            "",
            "Trooth publishes a six-dimension scorecard per source. These nodes hold the cards "
            "as events and answer from them; the pages are Trooth's.",
            "",
        ]
        for _sid, c in sorted(cards.items()):
            extra = ""
            if c.get("freshness_p95_s") is not None:
                extra += f", freshness p95 {c['freshness_p95_s']}s"
            if c.get("completeness_pct") is not None:
                extra += f", completeness {c['completeness_pct']}%"
            lines.append(
                f"- [{c['source_name']}]({c['page_url']}) — scored {c['generated_at']}{extra}"
            )
        lines.append("")
    if emblems:
        lines += [
            "## UI outputs used: Modafied emblems",
            "",
            f"[Modafied]({MODAFIED_SITE}/) is an independent benchmark, funded by Trooth and "
            "measured by the same code for every source. Each emblem below is Modafied's own, "
            "verified against its manifest before it was held, and linked to its scorecard.",
            "",
        ]
        for _sid, e in sorted(emblems.items()):
            lines += [markdown_emblem(e), ""]
        notice = next((e["notice"] for e in emblems.values() if e.get("notice")), "")
        if notice:
            lines += [f"> {notice}", ""]
    lines += [
        "## Answers",
        "",
        "Every answer these nodes give cites the events above by id; "
        "`kourob trace <receipt>` walks a receipt back to them.",
        "",
    ]
    return "\n".join(lines)


__all__ = ["MODAFIED_SITE", "TROOTH_SITE", "credits_markdown", "held", "markdown_emblem"]
